# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sudarshan/system-monitor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sudarshan/system-monitor/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sudarshan/system-monitor/build/CMakeFiles /home/sudarshan/system-monitor/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sudarshan/system-monitor/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SystemMonitor

# Build rule for target.
SystemMonitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SystemMonitor
.PHONY : SystemMonitor

# fast build rule for target.
SystemMonitor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/build
.PHONY : SystemMonitor/fast

#=============================================================================
# Target rules for targets named SystemMonitor_autogen_timestamp_deps

# Build rule for target.
SystemMonitor_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SystemMonitor_autogen_timestamp_deps
.PHONY : SystemMonitor_autogen_timestamp_deps

# fast build rule for target.
SystemMonitor_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor_autogen_timestamp_deps.dir/build.make CMakeFiles/SystemMonitor_autogen_timestamp_deps.dir/build
.PHONY : SystemMonitor_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SystemMonitor_autogen

# Build rule for target.
SystemMonitor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SystemMonitor_autogen
.PHONY : SystemMonitor_autogen

# fast build rule for target.
SystemMonitor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor_autogen.dir/build.make CMakeFiles/SystemMonitor_autogen.dir/build
.PHONY : SystemMonitor_autogen/fast

SystemMonitor_autogen/mocs_compilation.o: SystemMonitor_autogen/mocs_compilation.cpp.o
.PHONY : SystemMonitor_autogen/mocs_compilation.o

# target to build an object file
SystemMonitor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/SystemMonitor_autogen/mocs_compilation.cpp.o
.PHONY : SystemMonitor_autogen/mocs_compilation.cpp.o

SystemMonitor_autogen/mocs_compilation.i: SystemMonitor_autogen/mocs_compilation.cpp.i
.PHONY : SystemMonitor_autogen/mocs_compilation.i

# target to preprocess a source file
SystemMonitor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/SystemMonitor_autogen/mocs_compilation.cpp.i
.PHONY : SystemMonitor_autogen/mocs_compilation.cpp.i

SystemMonitor_autogen/mocs_compilation.s: SystemMonitor_autogen/mocs_compilation.cpp.s
.PHONY : SystemMonitor_autogen/mocs_compilation.s

# target to generate assembly for a file
SystemMonitor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/SystemMonitor_autogen/mocs_compilation.cpp.s
.PHONY : SystemMonitor_autogen/mocs_compilation.cpp.s

src/MainWindow.o: src/MainWindow.cpp.o
.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/MainWindow.cpp.o
.PHONY : src/MainWindow.cpp.o

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/monitors/CpuMonitor.o: src/monitors/CpuMonitor.cpp.o
.PHONY : src/monitors/CpuMonitor.o

# target to build an object file
src/monitors/CpuMonitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/CpuMonitor.cpp.o
.PHONY : src/monitors/CpuMonitor.cpp.o

src/monitors/CpuMonitor.i: src/monitors/CpuMonitor.cpp.i
.PHONY : src/monitors/CpuMonitor.i

# target to preprocess a source file
src/monitors/CpuMonitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/CpuMonitor.cpp.i
.PHONY : src/monitors/CpuMonitor.cpp.i

src/monitors/CpuMonitor.s: src/monitors/CpuMonitor.cpp.s
.PHONY : src/monitors/CpuMonitor.s

# target to generate assembly for a file
src/monitors/CpuMonitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/CpuMonitor.cpp.s
.PHONY : src/monitors/CpuMonitor.cpp.s

src/monitors/MemoryMonitor.o: src/monitors/MemoryMonitor.cpp.o
.PHONY : src/monitors/MemoryMonitor.o

# target to build an object file
src/monitors/MemoryMonitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/MemoryMonitor.cpp.o
.PHONY : src/monitors/MemoryMonitor.cpp.o

src/monitors/MemoryMonitor.i: src/monitors/MemoryMonitor.cpp.i
.PHONY : src/monitors/MemoryMonitor.i

# target to preprocess a source file
src/monitors/MemoryMonitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/MemoryMonitor.cpp.i
.PHONY : src/monitors/MemoryMonitor.cpp.i

src/monitors/MemoryMonitor.s: src/monitors/MemoryMonitor.cpp.s
.PHONY : src/monitors/MemoryMonitor.s

# target to generate assembly for a file
src/monitors/MemoryMonitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/monitors/MemoryMonitor.cpp.s
.PHONY : src/monitors/MemoryMonitor.cpp.s

src/widgets/LogsTab.o: src/widgets/LogsTab.cpp.o
.PHONY : src/widgets/LogsTab.o

# target to build an object file
src/widgets/LogsTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/LogsTab.cpp.o
.PHONY : src/widgets/LogsTab.cpp.o

src/widgets/LogsTab.i: src/widgets/LogsTab.cpp.i
.PHONY : src/widgets/LogsTab.i

# target to preprocess a source file
src/widgets/LogsTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/LogsTab.cpp.i
.PHONY : src/widgets/LogsTab.cpp.i

src/widgets/LogsTab.s: src/widgets/LogsTab.cpp.s
.PHONY : src/widgets/LogsTab.s

# target to generate assembly for a file
src/widgets/LogsTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/LogsTab.cpp.s
.PHONY : src/widgets/LogsTab.cpp.s

src/widgets/MetricsTab.o: src/widgets/MetricsTab.cpp.o
.PHONY : src/widgets/MetricsTab.o

# target to build an object file
src/widgets/MetricsTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/MetricsTab.cpp.o
.PHONY : src/widgets/MetricsTab.cpp.o

src/widgets/MetricsTab.i: src/widgets/MetricsTab.cpp.i
.PHONY : src/widgets/MetricsTab.i

# target to preprocess a source file
src/widgets/MetricsTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/MetricsTab.cpp.i
.PHONY : src/widgets/MetricsTab.cpp.i

src/widgets/MetricsTab.s: src/widgets/MetricsTab.cpp.s
.PHONY : src/widgets/MetricsTab.s

# target to generate assembly for a file
src/widgets/MetricsTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/MetricsTab.cpp.s
.PHONY : src/widgets/MetricsTab.cpp.s

src/widgets/ProcessesTab.o: src/widgets/ProcessesTab.cpp.o
.PHONY : src/widgets/ProcessesTab.o

# target to build an object file
src/widgets/ProcessesTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/ProcessesTab.cpp.o
.PHONY : src/widgets/ProcessesTab.cpp.o

src/widgets/ProcessesTab.i: src/widgets/ProcessesTab.cpp.i
.PHONY : src/widgets/ProcessesTab.i

# target to preprocess a source file
src/widgets/ProcessesTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/ProcessesTab.cpp.i
.PHONY : src/widgets/ProcessesTab.cpp.i

src/widgets/ProcessesTab.s: src/widgets/ProcessesTab.cpp.s
.PHONY : src/widgets/ProcessesTab.s

# target to generate assembly for a file
src/widgets/ProcessesTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SystemMonitor.dir/build.make CMakeFiles/SystemMonitor.dir/src/widgets/ProcessesTab.cpp.s
.PHONY : src/widgets/ProcessesTab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SystemMonitor_autogen"
	@echo "... SystemMonitor_autogen_timestamp_deps"
	@echo "... SystemMonitor"
	@echo "... SystemMonitor_autogen/mocs_compilation.o"
	@echo "... SystemMonitor_autogen/mocs_compilation.i"
	@echo "... SystemMonitor_autogen/mocs_compilation.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/monitors/CpuMonitor.o"
	@echo "... src/monitors/CpuMonitor.i"
	@echo "... src/monitors/CpuMonitor.s"
	@echo "... src/monitors/MemoryMonitor.o"
	@echo "... src/monitors/MemoryMonitor.i"
	@echo "... src/monitors/MemoryMonitor.s"
	@echo "... src/widgets/LogsTab.o"
	@echo "... src/widgets/LogsTab.i"
	@echo "... src/widgets/LogsTab.s"
	@echo "... src/widgets/MetricsTab.o"
	@echo "... src/widgets/MetricsTab.i"
	@echo "... src/widgets/MetricsTab.s"
	@echo "... src/widgets/ProcessesTab.o"
	@echo "... src/widgets/ProcessesTab.i"
	@echo "... src/widgets/ProcessesTab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

