// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_MainWindow.cpp"
#include "RZ4CM6YYJ6/moc_LogsTab.cpp"
#include "RZ4CM6YYJ6/moc_MetricsTab.cpp"
#include "RZ4CM6YYJ6/moc_ProcessesTab.cpp"
